Repository Diary-SPO/core, pull requests merged in 2023-09, with the labels that each got.

#23 feat(add-user-info): добавлена инфа о юзере и мелкие улучшения
  frontend/src/AppWrapper.tsx
  frontend/src/components/LessonCard.tsx
  frontend/src/components/MarksByGroup.tsx
  frontend/src/components/ScheduleGroup.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/Tabbar.tsx
  frontend/src/components/UserInfo.tsx
  frontend/src/modals/ModalRoot.tsx
  frontend/src/utils/setDefaultMarkIfEmpty.ts
  frontend/src/views/LoginForm.tsx
  frontend/src/views/Marks.tsx
  shared/index.ts
Labels: enhancement

#29 feat(fix-time): fix time color etc
  frontend/index-b2.1.html
  frontend/src/components/LessonCard.tsx
  frontend/src/components/MarksByGroup.tsx
  frontend/src/components/SubtitleWithBorder.tsx
  frontend/src/components/TimeRemaining.tsx
  frontend/src/components/UserInfo.tsx
  frontend/vite.config.ts
  frontend/vk-hosting-config.json
Labels: bug, enhancement

#30 feat(cors-fix): using cors
  backend/index.ts
  backend/src/middleware/index.ts
  backend/src/routes/lessons.route.ts
  backend/src/routes/login.route.ts
  frontend/build.zip
Labels: bug

#32 feat(add-days-etc): новое отображение дней + улучшена работа периодов
  frontend/index-b3.3.html
  frontend/src/components/LessonCard.tsx
  frontend/src/components/SubtitleWithBorder.tsx
  frontend/src/modals/ModalRoot.tsx
  frontend/src/utils/formatLessonDate.ts
  frontend/src/utils/isToday.ts
  frontend/src/views/Schedule.tsx
Labels: enhancement

#35 feat(add-week-button): Добавлена кнопка для возвращения на текущую неделю
  frontend/src/App.tsx
  frontend/src/AppWrapper.tsx
  frontend/src/components/LessonCard.tsx
  frontend/src/components/MarksByGroup.tsx
  frontend/src/components/UI/Epic.tsx
  frontend/src/components/UI/ExplanationTooltip.tsx
  frontend/src/components/UI/Mark.tsx
  frontend/src/components/UI/NotFound.tsx
  frontend/src/components/UI/PanelHeaderWithBack.tsx
  frontend/src/components/UI/Sidebar.tsx
  frontend/src/components/UI/Suspense.tsx
  frontend/src/components/UI/Tabbar.tsx
  frontend/src/components/data.ts
  frontend/src/hooks/useSnackbar.tsx
  frontend/src/main.tsx
  frontend/src/methods/bridge/appStorageSet.ts
  frontend/src/modals/ModalRoot.tsx
  frontend/src/utils/isToday.ts
  frontend/src/utils/truncateText.ts
  frontend/src/views/Contacts.tsx
  frontend/src/views/LoginForm.tsx
  frontend/src/views/Marks.tsx
  frontend/src/views/Schedule.tsx
  frontend/src/views/Settings.tsx
Labels: enhancement

#41 feat(links): add textToLink etc
  frontend/src/components/LessonCard.tsx
  frontend/src/components/UserInfo.tsx
  frontend/src/methods/bridge/appStorageSet.ts
  frontend/src/modals/LessonModal.tsx
  frontend/src/modals/ModalRoot.tsx
  frontend/src/modals/data.ts
  frontend/src/utils/textToLink.tsx
Labels: enhancement

#42 feat(marks-by-day): добавлены оценки на главную etc
  backend/index.ts
  frontend/src/components/LessonCard.tsx
  frontend/src/components/MarksByGroup.tsx
  frontend/src/components/UI/CalendarRange.tsx
  frontend/src/components/UI/Mark/index.css
  frontend/src/components/UI/Mark/index.tsx
  frontend/src/components/UI/MarksByDay/index.css
  frontend/src/components/UI/MarksByDay/index.tsx
  frontend/src/components/UI/Sidebar.tsx
  frontend/src/components/UI/Tabbar.tsx
  frontend/src/methods/index.ts
  frontend/src/methods/server/getMarks.ts
  frontend/src/methods/server/getPerformance.ts
  frontend/src/utils/calculateAverageMark.ts
  frontend/src/views/Schedule.tsx
  shared/index.ts
Labels: enhancement

#47 add: добавлена поддержка домашних заданий
  frontend/src/components/UI/Mark/index.tsx
  frontend/src/modals/LessonModal.tsx
  frontend/src/utils/setDefaultMark.ts
  frontend/vite.config.ts
  shared/index.ts
Labels: enhancement

#52 fix-marks
  frontend/src/components/UI/MarksByDay/index.tsx
Labels: bug

#53 Fix marks order / names
  frontend/src/components/UI/MarksByDay/index.tsx
  frontend/src/views/Notifications.tsx
Labels: bug

#57 new component for all marks
  frontend/src/components/MarksByGroup.tsx
  frontend/src/components/UI/Mark/index.tsx
  frontend/src/components/UI/Summary.tsx
  frontend/src/components/UI/Tabbar.tsx
  frontend/src/components/UserInfo.tsx
  frontend/src/utils/logOut.ts
  frontend/src/views/Marks.tsx
Labels: enhancement
