Repository Diary-SPO/core, pull requests merged in 2023-11, with the labels that each got.

#85 chore: little refactor
  CNAME
  src/components/UI/AttestationSubjects/LoadingData.tsx
  src/components/UI/AttestationSubjects/SubjectsList.tsx
  src/utils/setLessonDetails.ts
  src/views/Attestation.tsx
Labels: chore

#87 hotfix: fix TimeRemaining error
  src/components/ScheduleGroup.tsx
  src/components/UI/Lesson/LessonCard.tsx
  src/components/UI/Lesson/LessonSubtitle.tsx
  src/components/UI/TimeRemaining.tsx
  src/utils/formatted/convertStringToTime.ts
  src/utils/index.ts
Labels: bug

#82 feat: custom domain support & little fixes
  src/components/UI/Marks/MarksByGroup.tsx
  src/utils/marks/getBackgroundColor.ts
  src/views/Schedule.tsx
Labels: enhancement, chore

#88 feature: add tests
  .github/workflows/test.yml
  .gitignore
  __tests__/base/b.test.tsx
  __tests__/base/mocs.ts
  __tests__/formatted/f.test.ts
  __tests__/i.test.ts
  __tests__/marks/m.test.ts
  __tests__/marks/mocks.ts
  __tests__/store/s.test.ts
  package.json
  src/components/ScheduleGroup.tsx
  src/components/UI/AttestationSubjects/SubjectCard.tsx
  src/components/UI/Lesson/LessonCard.tsx
  src/components/UI/Lesson/LessonCell.tsx
  src/components/UI/Marks/MarksList.tsx
  src/components/UI/Marks/NoData.tsx
  src/components/UI/MarksByDay/LessonGrades.tsx
  src/components/UI/SubtitleWithBorder/index.tsx
  src/components/UI/TimeRemaining.tsx
  src/components/UserInfo.tsx
  src/main.tsx
  src/store/index.ts
  src/utils/formatted/convertStringToTime.ts
  src/utils/formatted/formatLessonDate.ts
  src/utils/formatted/formatLessonName.ts
  src/utils/formatted/formatStatisticsData.ts
  src/utils/getTimeRemaining.ts
  src/utils/handleResponse.ts
  src/utils/marks/calculateAverageMark.ts
  src/utils/marks/createSubjectMarksMap.ts
  src/utils/marks/extractMarksByDay.ts
  src/utils/marks/getSize.ts
  src/utils/setLessonDetails.ts
  src/utils/truncateString.ts
  src/views/Marks.tsx
  src/views/Schedule.tsx
  vite.config.ts
  yarn.lock
Labels: enhancement

#92 feat: new shared & update deps
  __tests__/base/mocs.ts
  __tests__/formatted/f.test.ts
  __tests__/marks/m.test.ts
  __tests__/marks/mocks.ts
  package.json
  src/components/ScheduleGroup.tsx
  src/components/UI/AttestationSubjects/SubjectCard.tsx
  src/components/UI/AttestationSubjects/types.ts
  src/components/UI/Lesson/LessonCard.tsx
  src/components/UI/Lesson/LessonCell.tsx
  src/components/UI/Lesson/LessonSubtitle.tsx
  src/components/UI/Marks/MarksByGroup.tsx
  src/components/UI/Marks/MarksList.tsx
  src/components/UI/MarksByDay/index.tsx
  src/components/UserInfo.tsx
  src/methods/server/getAds.ts
  src/methods/server/getAttestation.ts
  src/methods/server/getCollegeInfo.ts
  src/methods/server/getLessons.ts
  src/methods/server/getPerformance.ts
  src/modals/LessonModal/LessonGrade.tsx
  src/modals/LessonModal/LessonMainInfo.tsx
  src/modals/LessonModal/LessonTasks.tsx
  src/modals/LessonModal/index.tsx
  src/modals/data.ts
  src/store/useModal.tsx
  src/utils/formatted/formatStatisticsData.ts
  src/utils/marks/calculateAverageMark.ts
  src/utils/marks/createSubjectMarksMap.ts
  src/utils/marks/extractMarksByDay.ts
  src/utils/marks/setDefaultMark.ts
  src/utils/setLessonDetails.ts
  src/views/Attestation.tsx
  src/views/LoginForm.tsx
  src/views/Marks.tsx
  src/views/Notifications.tsx
  src/views/Schedule.tsx
  yarn.lock
Labels: dependencies
