Repository Diary-SPO/core, pull requests merged in 2024-01, with the labels that each got.

#97 Updates: ready to 2 semester
  biome.json
  package.json
  src/AppWrapper.tsx
  src/AuthProvider.tsx
  src/components/TechWorking.tsx
  src/components/UI/Marks/MarksByGroup.tsx
  src/components/UI/Marks/NoData.tsx
  src/components/UI/Summary.tsx
  src/main.tsx
  src/methods/server/requestToSecondServer.ts
  src/types/index.ts
  src/utils/formatted/formatStatisticsData.ts
  src/utils/marks/calculateAverageMark.ts
  src/utils/marks/createSubjectMarksMap.ts
  src/utils/marks/extractMarksByDay.ts
  src/utils/sortByDay.ts
  src/views/Attestation.tsx
  src/views/LoginForm.tsx
  src/views/NotFound.tsx
  src/views/Schedule.tsx
  yarn.lock
Labels: enhancement

#104 Refactor files
  __tests__/formatted/f.test.ts
  src/components/UI/Mark/helpers.ts
  src/components/UI/Mark/index.tsx
  src/components/index.tsx
  src/config/index.ts
  src/hooks/useRateLimitExceeded.tsx
  src/hooks/useSnackbar.tsx
  src/methods/index.ts
  src/methods/makeRequest.ts
  src/methods/requestToSecondServer.ts
  src/methods/server/getAds.ts
  src/methods/server/getAttestation.ts
  src/methods/server/getCollegeInfo.ts
  src/methods/server/getLessons.ts
  src/methods/server/getPerformance.ts
  src/methods/server/helpers.ts
  src/types/index.ts
  src/utils/formatted/convertStringToTime.ts
  src/utils/formatted/formatDate.ts
  src/utils/index.ts
  src/utils/isToday.ts
  src/utils/marks/calculateAverageMark.ts
  src/utils/marks/createSubjectMarksMap.ts
  src/utils/marks/getSize.ts
  src/utils/marks/setDefaultMark.ts
  src/utils/textToLink.tsx
  src/views/LoginForm.tsx
  src/views/Marks/MarksByGroup/AverageMarkCell.tsx
  src/views/Marks/MarksByGroup/helpers.tsx
  src/views/Marks/helpers.ts
  src/views/Marks/index.tsx
  src/views/Notifications.tsx
  src/views/Schedule/MarksByDay/LessonGrades.tsx
  src/views/Schedule/ScheduleGroup/LessonCard/LessonCell/LessonSubtitle/TimeRemaining.tsx
  src/views/Schedule/ScheduleGroup/LessonCard/LessonCell/LessonSubtitle/helpers.ts
  src/views/Schedule/ScheduleGroup/LessonCard/LessonCell/LessonSubtitle/index.tsx
  src/views/Schedule/ScheduleGroup/LessonCard/helpers.ts
  src/views/Schedule/ScheduleGroup/LessonCard/index.tsx
  src/views/Schedule/utils.ts
  src/views/Settings.tsx
Labels: enhancement

#106 feat: update config and schedule
  __tests__/base/b.test.tsx
  __tests__/formatted/f.test.ts
  __tests__/i.test.ts
  package.json
  src/app/AppWrapper/App/ModalRoot/index.tsx
  src/app/AppWrapper/App/ModalRoot/modals/LessonModal/__tests__/i.test.ts
  src/app/AppWrapper/App/ModalRoot/modals/LessonModal/__tests__/mocs.ts
  src/app/AppWrapper/App/index.tsx
  src/app/AppWrapper/AuthProvider.tsx
  src/components/UI/ExplanationTooltip.tsx
  src/components/UI/Mark/__tests__/i.test.ts
  src/config/env.ts
  src/config/index.ts
  src/hooks/useSnackbar.tsx
  src/methods/makeRequest.ts
  src/methods/server/__tests__/i.test.ts
  src/store/__tests__/i.test.ts
  src/types/index.ts
  src/utils/handleResponse.ts
  src/utils/handleResponse/__test__/i.test.ts
  src/utils/handleResponse/index.ts
  src/utils/logOut/__tests__/i.test.ts
  src/utils/logOut/index.ts
  src/utils/textToLink/__test__/i.test.tsx
  src/utils/textToLink/__test__/mocs.ts
  src/utils/textToLink/index.tsx
  src/views/Contacts/data.ts
  src/views/Contacts/index.tsx
  src/views/LoginForm.tsx
  src/views/Marks/MarksByGroup/__tests__/i.test.ts
  src/views/Marks/MarksByGroup/__tests__/mocks.ts
  src/views/Marks/__tests__/i.test.ts
  src/views/Marks/index.tsx
  src/views/Notifications.tsx
  src/views/Schedule/MarksByDay/__test__/i.test.ts
  src/views/Schedule/ScheduleAsideButtons.tsx
  src/views/Schedule/ScheduleGroup/LessonCard/LessonCell/LessonSubtitle/__test__/i.test.ts
  src/views/Schedule/ScheduleGroup/LessonCard/__test__/i.test.ts
  src/views/Schedule/index.tsx
  src/views/Settings.tsx
  yarn.lock
Labels: packages, (╯°□°), chore, bug-fix, refactor

#108 feat: use VKUI v6 & improve error handlings
  package.json
  src/app/AppWrapper/App/ModalRoot/modals/LessonModal/LessonMainInfo.tsx
  src/app/AppWrapper/App/ModalRoot/modals/LessonModal/__tests__/mocs.ts
  src/app/AppWrapper/App/ModalRoot/modals/LessonModal/helpers.ts
  src/app/AppWrapper/App/ModalRoot/modals/LessonModal/index.tsx
  src/app/AppWrapper/App/index.tsx
  src/app/AppWrapper/AuthProvider.tsx
  src/app/AppWrapper/index.tsx
  src/components/UI/PanelHeaderWithBack.tsx
  src/main.tsx
  src/methods/makeRequest.ts
  src/methods/requestToSecondServer.ts
  src/utils/handleResponse/index.tsx
  src/utils/index.tsx
  src/views/Attestation/index.tsx
  src/views/LoginForm.tsx
  src/views/Marks/index.tsx
  src/views/Notifications.tsx
  src/views/Schedule/MarksByDay/LessonGrades.tsx
  src/views/Schedule/ScheduleGroup/LessonCard/LessonHeader.tsx
  src/views/Schedule/index.tsx
  src/views/Settings.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: enhancement, dependencies, bug-fix

#116 feat: add rsbuild & own hash method, rm jshashes & vite
  .env.development
  .gitignore
  index.html
  package.json
  rsbuild.config.ts
  src/components/UI/PanelHeaderWithBack.tsx
  src/config/env.ts
  src/hooks/index.tsx
  src/hooks/useRateLimitExceeded.tsx
  src/hooks/useSnackbar.tsx
  src/index.tsx
  src/libs/index.ts
  src/libs/jshashes.ts
  src/utils/handleResponse/__test__/i.test.ts
  src/utils/handleResponse/index.tsx
  src/views/Attestation/index.tsx
  src/views/Contacts/index.tsx
  src/views/LoginForm.tsx
  src/views/Marks/index.tsx
  src/views/Notifications.tsx
  src/views/Schedule/ScheduleAsideButtons.tsx
  src/views/Schedule/ScheduleGroup/LessonCard/index.tsx
  src/views/Schedule/index.tsx
  src/views/Settings.tsx
  src/views/TechWorking.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: enhancement, packages, (╯°□°)

#121 refactor: улучшить makeRequest
  .env.development
  src/config/env.ts
  src/methods/makeRequest.ts
  src/methods/requestToSecondServer.ts
Labels: chore, refactor

#122 chore: rm sut
  rsbuild.config.ts
  src/index.tsx
  src/views/Schedule/ScheduleGroup/LessonCard/index.tsx
  src/views/Schedule/utils.ts
Labels: chore

#124 feat: create get-size workflow
  .github/workflows/get-size.yml
  package.json
  yarn.lock
Labels: enhancement

#123 feat: add css modules for VKUI
  .github/workflows/get-size.yml
  package.json
  rsbuild.config.ts
  src/config/env.ts
  src/index.tsx
  yarn.lock
Labels: enhancement
